name: Geen tijdelijke LaTeX-bestanden

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths:
      - 'tekst/**'
      - '.github/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'tekst/**'
      - '.github/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Check for auxiliary files
        run: |
          if [ -f *.aux ] || [ -f *.bbl ] || [ -f *.blg ] || [ -f *.fdb_latexmk ] || [ -f *.fls ] || [ -f *.lof ] || [ -f *.log ] || [ -f *.lot ] || [ -f *.pdf ] || [ -f *.synctex.gz ];
          then
            echo "De repository bevat tijdelijke LaTeX-bestanden! Verwijder deze!"
            exit 1
          else
            echo "De repository bevat geen tijdelijke LaTeX-bestanden! De repository is clean!"
            exit 0
          fi
